package com.googleintreview;

public class Abbrevation {

    public static void main(String []args) {
        String testData = "SVAHHHMVIIDYIcOSHMDUAVJRIBxBZQSUBIVEBHfVTZVSHATUYDJGDRRUBQFHEEEUZLQGXTNKFWUYBAeFKUHSFLZEUINBZYRIXOPYYXAEZZWELUPIEIWGZHEIYIROLQLAVHhMKRDSOQTJYYLTCTSIXIDAnPIHNXENWFFZFJASRZRDAPVYPAViVBLVGRHObnwlcyprcfhdpfjkyvgyzpovsgvlqbhtwrucvszaqinbgeafuswkjrcexvyzq\n" +
                "SVAHHHMVIIDYIOSHMDUAVJRIBBZQSUBIVEBHVTZVSHATUYDJGDRRUBQFHEEEUZLQGXTNKFWUYBAFKUHSFLZEUINBZYRIXOPYYXAEZZWELUPIEIWGZHEIYIROLQLAVHMKRDSOQTJYYLTCTSIXIDAPIHNXENWFFZFJASRZRDAPVYPAVVBLVGRHO\n" +
                "WIRUQDCAQUTtZVVAzLKMVWIOXLBESKUQSUOAEHEFMMhwwiyrqhaiixtqhaynwcsoihabohxepjbyroaglaobfwwzymlijsdhdsqlxazqggesnhdnblqbgouwjyowpjfmbshfenrtcoqyszmpamoaehnepi\n" +
                "WIRUQDCAQUTZVVALKMVWIOXLBESKUQSUOAEHEFMM\n" +
                "EPgDKTFPMjMXHIOYEFAFDWqNXNXCYOQwXOYDHNEJGBIKZYxiPrUALJFEVMRJEVKWZXNEMMPWAXMCAOjAsAGBhYTTKZHITGSYQQGyUMSLVDSFWOLJICNEWUBOMNOBOuFKUMREWGTObXRFKORKVUWNZMWCPXJGQNJETWHyKPNBYXLfWYUXQIXVVHFMGPNLcOKGRQFCADNCRmfBSbZJwLSWEpXvELKSDUMKsZlUHNYFEf\n" +
                "EPDKTFPMMXHIOYEFAFDWNXNXCYOQXOYDHNEJGBIKZYPUALJFEVMRJEVKWZXNEMMPWAXMCAOAAGBYTTKZHITGSYQQGUMSLVDSFWOLJICNEWUBOMNOBOFKUMREWGTOXRFKORKVUWNZMWCPXJGQNJETWHKPNBYXLWYUXQIXVVHFMGPNLOKGRQFCADNCRBSZJLSWEXELKSDUMKZUHNYFE\n" +
                "XWUTAMOTDYULFGPIZVLGEVUWTNCDFWMDMGOADGOGYWIKACOARBPBGCCEQZWCURWCDSFCCWVIRZJNVYWUXHNXABVQXUNGEQWSDJAMIQBDLRPHUVLMRXLDJIWKRWBDKIACCPGVXINRCSQNBWDVEVNVLGLSCCSALXRKICOGTOHYVXUUSMZCFMXUDEESPXPMBXRJSQGWBUXMXNJDWZVLWPVTNSJYVTPCDTWSCJFINKELQCDVPPXZISqmgnrzwt\n" +
                "XWUTAMOTDYULFGPIZVLGEVUWTNCDFWMDMGOADGOGYWIKACOARBPBGCCEQZWCURWCDSFCCWVIRZJNVYWUXHNXABVQXUNGEQWSDJAMIQBDLRPHUVLMRXLDJIWKRWBDKIACCPGVXINRCSQNBWDVEVNVLGLSCCSALXRKICOGTOHYVXUUSMZCFMXUDEESPXPMBXRJSQGWBUXMXNJDWZVLWPVTNSJYVTPCDTWSCJFINKELQCDVPPXZIS\n" +
                "ALRIGJCXcFvZDTYFKWEEJSpayhsytgccieascmcgdejyunrwguxnuxneurbgfegnfpwbxsuolsxchasjegjdhwpzmwsyocdfnoiajkxugbliytqsthglmkawozahjsrhwdojwnpyycbbgxwxlsbslapslyphdxqjdgpplhcpug\n" +
                "ALRIGJCXFZDTYFKWEEJS\n" +
                "QGBOZKPCPMvEHGOFRWOXUOBCZDADERSPXNNJPOjMNUIHFZRACZJZWMZSNHJHJUYNCHSJKFDSLFBGKVYFJdkfxesjrixmzefcgewgrnn\n" +
                "QGBOZKPCPMEHGOFRWOXUOBCZDADERSPXNNJPOMNUIHFZRACZJZWMZSNHJHJUYNCHSJKFDSLFBGKVYFJ\n" +
                "lHJCJMWDFhSMRRZUKEUJxRZGVWATJtFRJPOOWkFEIEKsYBVILWARcDISwXAVPOYJHWRNHUQNDBUSRGIRIZTMHdXxodmgzkfxbpperyhufxymrphzkyzewldrijewezvobdshebnbtzxkupcvgrscyscrtxuwsmywoyuuxvyzxajccydqdngartsmbeptpabthasbgqccvzqvbmnokjwwqpzqcqqb\n" +
                "HJCJMWDFSMRRZUKEUJRZGVWATJFRJPOOWFEIEKYBVILWARDISXAVPOYJHWRNHUQNDBUSRGIRIZTMHX\n" +
                "TIJTQKlOTDVMEMKKMNYZtZIWLZOLJPPGCGTGTQBKILAXYMDXOOQMONZYXDZSgSVGJBmIIXXaTOLdMLbSCODRIUANIBRIQLVSXokicxpigmnirkneh\n" +
                "TIJTQKOTDVMEMKKMNYZZIWLZOLJPPGCGTGTQBKILAXYMDXOOQMONZYXDZSSVGJBIIXXTOLMLSCODRIUANIBRIQLVSX\n" +
                "MCLGDNAYZOVXJqJDAYrFHrBYZOUDBGEFfBTBZpNEZLURWEcDEBJQWIITUTNEteBHYYKOEGROMXmLEudSEWlUEFFTvINEHWNFObNOMWTNJMIyBEXTWBWOAKHNZKeEdCFuUSfAPXXZUZTDCVYmDFTSSGECgOHOQHSPEBUUWTspaviedpoeh\n" +
                "MCLGDNAYZOVXJJDAYFHBYZOUDBGEFBTBZNEZLURWEDEBJQWIITUTNEBHYYKOEGROMXLESEWUEFFTINEHWNFONOMWTNJMIBEXTWBWOAKHNZKECFUSAPXXZUZTDCVYDFTSSGECOHOQHSPEBUUWT\n" +
                "OVJZKEFYZSXQTYZGaQCQZNVMGVHRLVGJJBACNFCUWKGRDAcMJPTUAEHHSODHILKNQSTLTQOJHSKYOEBQQWNWTNCZCFOIURGTLESWSOAALWDIOWfCDMPJAROWSJJIOBMZYZVVXPMFAMINSWOLKOLJKRALZQMXBWTFRPHADEVUVFWHEMDSTRVBSKHARYXCQZCRZFAVYKKWQSOLKXCMpNMDMPWSOHUAGZBUOSWWIKVSNSdng\n" +
                "OVJZKEFYZSXQTYZGQCQZNVMGVHRLVGJJBACNFCUWKGRDAMJPTUAEHHSODHILKNQSTLTQOJHSKYOEBQQWNWTNCZCFOIURGTLESWSOAALWDIOWCDMPJAROWSJJIOBMZYZVVXPMFAMINSWOLKOLJKRALZQMXBWTFRPHADEVUVFWHEMDSTRVBSKHARYXCQZCRZFAVYKKWQSOLKXCMNMDMPWSOHUAGZBUOSWWIKVSNS";

        String []lines = testData.split("\n");
        for(int i=0; i<lines.length; i=i+2) {
            String a = lines[i];
            String b = lines[i+1];
            System.out.println(Abbrevation.abbreviation(a,b));
        }


    }
    /*
     * Complete the 'abbreviation' function below.
     *
     * The function is expected to return a STRING.
     * The function accepts following parameters:
     *  1. STRING a
     *  2. STRING b
     */

    public static String abbreviation(String a, String b) {
        // Write your code here
        // Case 1 : |a| = |b| and {b} = {a}, e.g. AbcDE, ABCDE
        // Case 2 : |a| < |b|   e.g. AbcDE, ABCDEF
        // Case 3 : |a| > |b| and {a} > {b}, e.g. AbcDEF, ABCDE
        // Case 4 : |a| = |b| and {b} != {a}, e.g. AbcDE, ABCDF or
        // Case 5 : |a| > |b| and {a} !> {b}, e.g. AbcDEF, ABCDE

        // Observations:
        // 1. b can be subsequence of a
        int bi = 0;
        for(int i=0; i<a.length(); i++) {
            char cha = a.charAt(i);
            if(bi < b.length()) {
                char chb = b.charAt(bi);


                if(Character.isUpperCase(cha) && chb != cha) {
                    return "NO";
                }
                if(chb == Character.toUpperCase(cha)) {
                    bi++;
                }
            } else {
                if(Character.isUpperCase(cha)) {
                    return "NO";
                }
            }

        }
        if(bi != b.length()) {
            return "NO";
        } else
            return "YES";

    }

}
